version: "3"
networks:
  geoserver-network:
    driver: bridge
services:
  geoserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PLUGIN_DYNAMIC_URLS: "https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.2/extensions/geoserver-2.21.2-authkey-plugin.zip https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.2/extensions/geoserver-2.21.2-vectortiles-plugin.zip"
        GEOSERVER_WEBAPP_SRC: "https://sourceforge.net/projects/geoserver/files/GeoServer/2.21.2/geoserver-2.21.2-war.zip/download#"
    container_name: geoserver
    ports:
      - 8082:8080
    networks:
      - geoserver-network
    volumes:
      - /root/geosolutions/data_dir:/var/geoserver/datadir
