services:
  geoserver:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GEOSERVER_WEBAPP_SRC: ./geoserver.war
        PLUG_IN_PATHS: ./plugins
    container_name: geoserver
    ports:
      - 8080:8080
    volumes:
      - gs_datadir:/var/geoserver/datadir

volumes:
  gs_datadir:
